version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: todo-app-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db-volumes:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: todo-app-backend
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npm run start:dev

volumes:
  db-volumes:
